### ISSUE TITLE
Precision settings don't seem to apply to equality constraints

### ISSUE THREAD

**Issue by rileyjmurray** [kul-forbes/scs#25] opened 2018-08-24 17:11 UTC
I recently tested SuperSCS on a moderate sized exponential cone problem (one that took 7 hours with SCS, and 13 seconds with an alpha version of MOSEK 9). The output of the run is below:
```
---------------------------------------------------------------------------------------
	SCS v1.3.3 - Superlinear Splitting Conic Solver (SuperSCS)
	Web: https://kul-forbes.github.io/scs
	(c) P. Sopasakis, K. Menounou, P. Patrinos, KU Leuven, 2017-8
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
---------------------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 706235
eps = 1.00e-08, alpha = 1.50, max_iters = 10000, normalize = 1, scale = 1.00
do_super_scs = 1, direction = 100, memory = 10
Variables n = 153181, constraints m = 306824
Cones:	primal zero / dual free vars: 1004
	linear vars: 153000
	exp vars: 152820, dual exp vars: 0
Setup time: 7.46e-01s
Running SuperSCS...
Allocated Memory: 188.20MB
---------------------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau |   FPR   | time (s)
---------------------------------------------------------------------------------------
     0|      inf       inf       nan      -inf       inf       inf  3.83e+02  4.73e-01 
   100| 1.75e+01  2.47e-01  8.13e-01 -9.55e+00 -5.35e-01  0.00e+00  2.82e+01  6.97e+01 
   200| 3.28e+01  3.70e-01  9.39e-01 -1.43e+01  9.66e-01  0.00e+00  3.45e+01  1.30e+02 
   300| 4.26e+01  4.70e-01  9.52e-01 -1.76e+01  2.05e+00  0.00e+00  3.96e+01  1.82e+02 
   400| 4.92e+01  5.66e-01  9.58e-01 -1.98e+01  2.85e+00  0.00e+00  4.42e+01  2.29e+02 
   500| 5.37e+01  6.35e-01  9.61e-01 -2.12e+01  3.51e+00  0.00e+00  4.72e+01  2.76e+02 
   548| 5.38e+01  6.61e-01  9.61e-01 -2.11e+01  3.71e+00  0.00e+00  4.84e+01  3.00e+02 
---------------------------------------------------------------------------------------
Status: Solved/Inaccurate
Timing: Solve time: 00:05:00.318
	Lin-sys: nnz in L factor: 1239735, avg solve time: 1.96e-02s
	Cones: avg projection time: 4.78e-01s
---------------------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.4266e-11, dist(y, K*) = 7.2271e-09, s'y/|s||y| = -9.8843e-12
|Ax + s - b|_2 / (1 + |b|_2) = 5.3802e+01
|A'y + c|_2 / (1 + |c|_2) = 6.6083e-01
|c'x + b'y| / (1 + |c'x| + |b'y|) = 9.6132e-01
---------------------------------------------------------------------------------------
c'x = -21.1421, -b'y = 3.7104
=======================================================================================
```

The cone constraints and complimentary slackness are handled with high precision (even higher than the 1e-8 precision requested), but the equality constraints are not respected.  Instead of having ``|Ax + s -b|`` on the order of 1e-8, it's on the order of 1e2! Rather than terminating after 5 minutes with a bad solution I would expect it to terminate after much longer (say, a couple hours) with a good solution.

Edit: the problem was formulated with cvxpy 1.0.8, using SuperSCS default settings within cvxpy (use_indirect=False, max_iters=10000).

**Comment by alphaville** [comment] 2018-08-28 06:12
@rileyjmurray The default value of parameter `max_time_milliseconds` is set to `300000`, which means that the solver will terminate after 5 minutes. The reason for having this option, is that it allows for a more meaningful comparison of different solvers as opposed to the maximum number of iterations (different algorithms have different per-iteration computation cost). 

It seems that when the maximum execution time is reached/exceeded, the termination conditions are not checked.

**Comment by alphaville** [comment] 2018-08-28 12:59
@rileyjmurray  Actually, the status of the problem is `Solved/Inaccurate` which is correct because the solver has not converged. In fast, in 5 minutes, just 548 iterations have been executed which are clearly not adequate for convergence. The issue here is that SuperSCS terminates because the maximum execution time is reaches (this can be overridden). Additionally, SuperSCS might not be able to reach such a high accuracy. You should try to increase `max_time_milliseconds`. SuperSCS should be able to converge at a moderate accuracy (around 1e-4 or 1e-5).

**Comment by alphaville** [comment] 2018-08-28 16:18
@rileyjmurray I believe you tried to solve the problem with the default options (Broyden directions with memory=10). I have now changed the default settings to use **Anderson's acceleration** with **memory=5**, which is known to yield superior performance. I believe that if you try again, you'll get faster convergence.

Since this issue is related to `max_time_milliseconds` I'll close it, but feel free to contact us if you encounter any other issues.

**Closed as completed by alphaville** 2018-08-28 16:18 UTC
Labels: bug, c

**Comment by rileyjmurray** [comment] 2018-08-28 16:25
@alphaville SuperSCS is the only solver supported by cvxpy that has a max time limit. I wrote the SuperSCS interface for cvxpy and I can easily change the cvxpy default for ``max_time_milliseconds`` to something much larger (e.g. 1e8). Would I have your blessing to do this? 

Note: if a cvxpy user specified ``max_time_milliseconds`` it would override the cvxpy default.

**Comment by alphaville** [comment] 2018-09-13 14:44
@rileyjmurray I apologize for the late reply. Yes, maybe you could set it to `1e8` to harmonize with the common practice of using only an upper bound on the number of iterations instead of runtime. By the way, there already is an interface between SuperSCS and CVXPy, but you need to download [this version of CVXPy](https://github.com/nishi951/cvxpy). Unfortunately, this does not fully support all features of SuperSCS, and has been abandoned. Nevertheless, it could be a starting point for you.

Are you modifying the source code of CVXPy?

**Comment by rileyjmurray** [comment] 2018-09-13 16:07
@alphaville I am happy to report that I have *already modified* the source code of cvxpy. As of cvxpy 1.0.8, SuperSCS is once again a supported solver (c.f. https://github.com/cvxgrp/cvxpy/pull/565). My request earlier was to make an additional change only for the ``max_time_milliseconds`` parameter.
