### ISSUE TITLE
Cannot make_scs on MacOS X 10.14.1

### ISSUE THREAD

**Issue by rocketdude** [kul-forbes/scs#27] opened 2018-11-27 04:52 UTC
Hello,

I'm using Mac OS X 10.14.1 with MATLAB 2018b. Calling `make` and `make run-test` on my system completes successfully. I'd like to use SuperSCS with CVX 3.0, but when I run `make_scs` in the matlab folder, here's the output:

```
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
[SuperSCS] Testing scs_direct... interrupt detected in factorization
ERROR: scs_init_priv failure
Failure:could not initialize work
Error using make_scs (line 129)
[direct] problem not solved
```

Any idea on how to get around this? On your MacOS machine, what version of MATLAB and CVX 3.0 work?

Thanks!

**Comment by alphaville** [comment] 2018-11-27 07:12
Hi @rocketdude. It seems that MEX compiles successfully, but then you get this message "interrupt detected in factorization," which implies that you interrupted the process, perhaps with a Ctrl+C. I don't have a MacOSX system. I've only compiled it on MacOSX using Travis, but, unfortunately, there's no way I can test MATLAB on OSX. Can you just try again after a `clean all` and see if the error persists?

**Comment by rocketdude** [comment] 2018-11-27 14:09
Hi @alphaville, Thanks for getting back to me quickly. Unfortunately, the problem persists even after a `clear all`. A few questions below.

1. Right now I'm trying to install previous versions of MATLAB to see if it works. Can I ask what versions are you using on your machine?

2. Alternatively, I also have a Ubuntu machine and a Windows machine. Have you tested SuperSCS in MATLAB+CVX for any of these machines? It'd be great if I can at least reproduce your working system.

3. Do we have to mess with `scs.mk` to work with MATLAB+CVX?  I tried the following:
- If I put the flag `MATLAB_MEX_FILE = 1`, then 
- link all my mex includes `/Applications/MATLAB_R2018b.app/extern/include/` in the `scs/include` folder, and then 
- `make` again
I get the following error:
```
Undefined symbols for architecture x86_64:
  "_mexEvalString_800", referenced from:
      _scs_print_header in scs.o
      _scs_print_summary in scs.o
      _scs_print_footer in scs.o
      _scs_init in scs.o
  "_mexPrintf_800", referenced from:
      _scs_init_sol in scs.o
      _scs_init_info in scs.o
      _scs_init_data in scs.o
      _scs_toc in util.o
      _scs_strtoc in util.o
      _scs_print_cone_data in util.o
      _scs_print_work in util.o
      ...
  "_mxCalloc_800", referenced from:
      _scs_update_work in scs.o
      _scs_init in scs.o
      _scs_init_sol in scs.o
      _scs_init_info in scs.o
      _scs_init_conework in cones.o
      _scs_cs_compress in cs.o
      _scs_cs_spalloc in cs.o
      ...
  "_mxFree_800", referenced from:
      _scs_get_dual_cone_dist in scs.o
      _scs_get_primal_cone_dist in scs.o
      _scs_update_work in scs.o
      _scs_print_footer in scs.o
      _scs_finish in scs.o
      _scs_init in scs.o
      _scs_free_data in util.o
      ...
  "_mxMalloc_800", referenced from:
      _scs_get_dual_cone_dist in scs.o
      _scs_get_primal_cone_dist in scs.o
      _scs_init_progress_data in scs.o
      _scs_failure in scs.o
      _scs_get_solution in scs.o
      _scs_print_footer in scs.o
      _scs_init in scs.o
      ...
  "_mxRealloc_800", referenced from:
      _amd_realloc in amd_global.o
  "_utIsInterruptPending", referenced from:
      _isInterrupted in ctrlc.o
  "_utSetInterruptEnabled", referenced from:
      _startInterruptListener in ctrlc.o
      _endInterruptListener in ctrlc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [out/libscsdir.dylib] Error 1
```

Thanks again.

**Comment by alphaville** [comment] 2018-11-27 14:41
You first need to do a simple `make` in your terminal. No need to modify `scs.mk` or `Makefile` and, for MATLAB, you don't need to set `MATLAB_MEX_FILE = 1`. 

The concept is that you first need to call `make` in your terminal. This will create a library with all necessary functions, which is found in `out/` (check out `out/libscsdir.a` and `out/libscsindir.a`). Then, from MATLAB, you compile MEX interfaces by calling `make_scs`. If this is successful, MATLAB creates two MEX files, namely `scs_direct.mexa64` and `scs_indirect.mexa64` (the file extensions are OS-specific). The MEX interface is implemented in `scs_mex.c`. The script `make_scs` takes care of linking to the library files of SuperSCS.

I have tried to compile SuperSCS on MacOSX using [clang](https://travis-ci.org/kul-forbes/scs/jobs/454514966) and [gcc](https://travis-ci.org/kul-forbes/scs/jobs/454514965) on travis (on online continuous integration system) and it works fine. However, unfortunately there's no way I can test SuperSCS on MATLAB using Travis.

I have tested SuperSCS from MATLAB 2017a on Ubuntu 14.04 and 16.04 and it works fine. 

I see, however, that MATLAB says that it has successfully compiled your MEX files. Can you try the following (after you do `make` in your terminal and `make_scs` in MATLAB)?

```matlab
clear all
rng('default')
rng(11);
m = 9; n = 4;
data.A = sparse(randn(m,n));
data.b = randn(m,1);
data.c = randn(n,1);
cones.q = m;

fprintf('[SuperSCS] Testing scs_indirect... ');
[x_indirect, y_indirect, s_indirect, info] = scs_indirect(data, cones,...
    struct('eps',1e-5,'do_super_scs',1,'rho_x',.001,'verbose',0));
assert(strcmp(info.status,'Solved')==1, '[indirect] problem not solved');
assert(abs(info.pobj-info.dobj)<1e-4, '[indirect] too high duality gap');
assert(info.relGap<1e-4, '[indirect] relative gap is too high');
assert(norm(x_direct-x_indirect, Inf) < 1e-4, 'direct-indirect discrepancy in x');
assert(norm(y_direct-y_indirect, Inf) < 1e-4, 'direct-indirect discrepancy in y');
assert(norm(s_direct-s_indirect, Inf) < 1e-4, 'direct-indirect discrepancy in s');
fprintf('OK!\n');
```

I'll dig a bit deeper into that "interrupt detected in factorization" and I'll get back to you.

**Comment by alphaville** [comment] 2018-11-27 18:54
I pushed a change (on `master`) that is likely to fix the issue. Can you please update (e.g., using `git pull origin master` or re-downloading SuperSCS) and let me know if the problem is resolved (you will have to run `make clean; make` (in terminal) and `make_scs` (in MATLAB) again.

---

*Note*: The error is thrown in [ldl.hL276](https://github.com/kul-forbes/scs/blob/master/linsys/direct/external/ldl.c#L276):

```c
if(isInterrupted()) {
    scs_printf("interrupt detected in factorization\n");
    return -1;
}
```

For some reason, `isInterrupted()` returns `true` or a non-zero value.

**Comment by alphaville** [comment] 2019-03-04 18:12
@rocketdude Have you resolved the issue? Please, let me know if you need any further help, otherwise, we can close this issue.

**Closed as completed** 2019-03-24 16:02 UTC
Labels: matlab

**Comment by rocketdude** [comment] 2019-03-27 21:22
@alphaville Sorry for the slow response. Please close the issue for now.

**Comment by hankyang94** [comment] 2020-12-22 17:45
Is this issue resolved? I have the same issue running make_scs in Matlab.

**Comment by rocketdude** [comment] 2021-01-17 14:03
The issue wasn't resolved for me. I had to work around this altogether unfortunately.
